### PR TITLE
Compile ConfigFiller usage example

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
To avoid code rotting, usage example is now compiled inside
an unittest.

### CODE REVIEW

**Review by mihails-strasuns — APPROVED** [review]

**Review by mihails-strasuns — CHANGES_REQUESTED** [review]
D2 failure:

```
./src/ocean/util/config/ConfigFiller.d(1331): Error: template instance LimitInit!(char[], "one", "one", "two", "three") does not match template declaration LimitInit(T, T init = T.init, Set...)
./src/ocean/util/config/ConfigFiller.d(1337): Error: function ocean.util.config.ConfigParser.ConfigParser.parseFile (string file_path = "etc/config.ini", bool clean_old = true) is not callable using argument types (char[])
./src/ocean/util/config/ConfigFiller.d(457): Error: static assert  "Tuple contains incompatible types! (string to char[] )"
./src/ocean/util/config/ConfigFiller.d(501):        instantiated from here: LimitCmp!(char[], null, defComp, "one", "two", "three")
./src/ocean/util/config/ConfigFiller.d(524):        instantiated from here: LimitInit!(char[], null, "one", "two", "three")
./src/ocean/util/config/ConfigFiller.d(1330):        instantiated from here: Limit!(char[], "one", "two", "three")
```

**Comment by nemanja-boric-sociomantic** [comment]
Fixed, thanks!

**Comment by mihails-strasuns** [comment]
Nope, not fixed :P

**Comment by mihails-strasuns** [comment]
@nemanja-boric-sociomantic ping

**Comment by nemanja-boric-sociomantic** [comment]
Thanks for the reminder!

**Comment by nemanja-boric-sociomantic** [comment]
Green.

**Review by mihails-strasuns — APPROVED** [review]

**Pull request merged**
