### PR TITLE
Don't run invariant on reset contiguous buffer

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
FYI @scott-gibson-sociomantic

**Comment by scott-gibson-sociomantic** [comment]
Working for me. I assume this will need some release notes.

**Comment by mihails-strasuns-sociomantic** [comment]
We don't have special release notes for bug fixes :)

**Comment by scott-gibson-sociomantic** [comment]
Ah ok, noted.

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Pull request merged**
