### PR TITLE
dub.sdl: Exclude deprecated modules from source file

### PR DESCRIPTION
**Pull request by Geod24**
Avoid deprecation warnings when compiling.

### CODE REVIEW

**Comment by joseph-wakeling-frequenz** [comment]
I'm not familiar with the modules, but ... is this wise?  Where do these deprecation warnings show up, if one doesn't either import the modules directly, or import modules that import them?

I'm concerned that excluding these source files in this way may either make them unusable by DUB projects or stop them being unittested via DUB.

**Comment by joseph-wakeling-frequenz** [comment]
I suppose the attitude might be "No new project should use these modules and by definition any DUB project using them is a new project", but generally it seems better to be comprehensive with testing in all circumstances, and bear the price of deprecations if necessary.

**Comment by Geod24** [comment]
Deprecated modules are not tested anyway:
https://github.com/sociomantic-tsunami/ocean/blob/af8c85cb6b92817946ae1d79d73c2ff4f2c5f50a/Build.mak#L44-L51

**Comment by Geod24** [comment]
Plus, none of those modules have tests anyway, they are merely thin wrappers for other modules

**Comment by joseph-wakeling-frequenz** [comment]
Fair enough, objections withdrawn :-)

**Comment by Geod24** [comment]
Ping @don-clugston-sociomantic

**Comment by don-clugston-sociomantic** [comment]
LGTM

**Pull request merged**
