### PR TITLE
Update to cachalot v3 image

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
Blocked until the final is out.

**Comment by leandro-lucarella-sociomantic** [comment]
Failing because of https://github.com/sociomantic-tsunami/beaver/pull/29 :grumpy:

**Comment by leandro-lucarella-sociomantic** [comment]
Beaver fix released, cachalot final released. Unblocking. This is ready to merge/review.

**Review by mihails-strasuns-sociomantic — APPROVED** [review]
Checked travis logs, all versions look correct

**Comment by mihails-strasuns-sociomantic** [comment]
Ah, should have probably targeted 3.3.x but not important enough to revert

**Pull request merged**
