### PR TITLE
D2: Use hasIndirections to determine AppendBuffer's parameter type

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
Before only class and interface was listen, but the issue is not actually that they are reference type,
but that they are aggregate. Before this patch, AppendBuffer would not instantiate with T = struct with
 mutable indirection.

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
`hasIndirections` from traits?

**Comment by mathias-lang-sociomantic** [comment]
:man_facepalming: 

Updated with `hasIndirections` + moar tests

**Comment by mihails-strasuns-sociomantic** [comment]
Red

**Comment by mathias-lang-sociomantic** [comment]
Woops, fixed

**Pull request merged**
