### PR TITLE
Upgrade tested upstream compiler version

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
(not yet available in d-apt, keeping PR as a reminder)

**Review by leandro-lucarella-sociomantic — APPROVED** [review]
:clap:

**Comment by mihails-strasuns-sociomantic** [comment]
Unblocking, restarting tests.

**Comment by mihails-strasuns-sociomantic** [comment]
Added commits to fix new deprecations

**Comment by mihails-strasuns-sociomantic** [comment]
Green

**Pull request merged**
