### PR TITLE
Support `scope cstring` in the FormatterSink

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
I couldn't run the test-suite locally but hopefully this works.

CC @Geod24

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
Argh that didn't work.

**Comment by Geod24** [comment]
There's a few places where `FormatterSink` should be used instead of ad-hoc delegates, e.g. in the `format` overloads of the `Appender` or in `Stdout`, so you'd have to fix that first.

**Comment by AndrejMitrovic** [comment]
I forgot to mention, there were too many breaking changes when I tried to change this alias. I'm not sure this is an easy change. It's only easy in our fork, since we exclude most files in the build.

**Comment by ben-palmer-sociomantic** [comment]
Seems to be failing the tests at the moment

**Comment by AndrejMitrovic** [comment]
@Geod24 do you wanna take over this one? You're the formatting expert.

**Comment by Geod24** [comment]
Just took a look, this will take a lot of fixes to make it work without breaking change, because the implementation of contravariance for delegate is botched :/
Might as well go into v6.x.x, but is there any interest to make such a release ?

**Comment by Geod24** [comment]
Done in: https://github.com/sociomantic-tsunami/ocean/pull/855

**Pull request closed without merging**
