### PR TITLE
Remove ocean.text.convert.Layout, Layout_tango and core.RuntimeTraits

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
Just a WIP at the moment, a few points need to be addressed.
Last user I know of are `StaticTrace`, `PeriodicTrace` and `Layout` (the non `_tango` module).
I also need to review documentation and write release notes. Since I'm trying to deprecate what I can in v3.x.x, some commit might be of interest to @mihails-strasuns-sociomantic when he does the next v4 rebase.

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
Will fix https://github.com/sociomantic-tsunami/ocean/issues/206

**Comment by mathias-lang-sociomantic** [comment]
@mihails-strasuns-sociomantic : I originally planned to deprecate `ocean.text.convert.Layout` but there's actually little value in that (no one use it anymore) should I just kill it along with `Layout_tango` ?
If that's the case, it means I'll submit the first 2 commits to v3.x.x, and the rest will go to v4.x.x

**Comment by mihails-strasuns-sociomantic** [comment]
I checked it all and that seems reasonable (and within neptune rules). My only request is to add release notes showing various code patterns with formatter sink to replace old layout patterns.

**Comment by mathias-lang-sociomantic** [comment]
Rebased, added release notes, and added removal of `RuntimeTraits`.

**Review by mihails-strasuns-sociomantic — APPROVED** [review]
I like it!

My only requirement is to have https://github.com/sociomantic-tsunami/ocean/issues/43 fixed first before we go full formatter.

**Comment by mathias-lang-sociomantic** [comment]
https://github.com/sociomantic-tsunami/ocean/pull/395

**Comment by mathias-lang-sociomantic** [comment]
Updated:
```diff
diff --git a/relnotes/42.migration.md b/relnotes/42.migration.md
index 170e92df..8fcbc497 100644
--- a/relnotes/42.migration.md
+++ b/relnotes/42.migration.md
@@ -7,4 +7,9 @@ All remaining users of `ocean.text.convert.Layout[_tango]` have been switched to
 For those which see their API affected, the most common use case of passing arguments will work just as before.
 Overriding the formatting function will not be possible anymore (as they are template), but redefinition is.
 
-However, forwarding variadic arguments won't work, so functions wishing to forward arguments must be defined as templated functions, as shown in `PeriodicTrace` release notes.
\ No newline at end of file
+However, forwarding variadic arguments won't work, so functions wishing to forward arguments must be defined as templated functions, as shown in `PeriodicTrace` release notes.
+
+Little difference in output is expected. Pointers will be formatted as fixed-length hexadecimal,
+associative arrays will be formatted as `[ Key: value...]` instead of `{ Key: value... }`,
+qualified (`const` / `immutable`) arguments will be correctly formatted, as well as structs,
+making the output consistent accross ocean (as the Logger module already uses the Formatter).
```

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Comment by mihails-strasuns-sociomantic** [comment]
Thanks!

**Pull request merged**
