### PR TITLE
Ignore `remaining_elements` in `FullQueryParamSet`

### LINKED ISSUE #559: Adapt `QueryParamSet.opApply` to not include `remaining_elements`
`opIn_r` doesn't report these extra values as being present, but `opApply` iterates over them. This is a pretty inconsistent API.

See discussion at https://github.com/sociomantic-tsunami/ocean/pull/558/files#r205364031.

### PR DESCRIPTION
**Pull request by mihails-strasuns**
Fixes #559

### CODE REVIEW

**Review by matthias-wende-sociomantic — COMMENTED** [review]
Wouldn't it be better to implement the `opIn` to get the consistency instead of removing the `opApply`? That probably depends on the general usage of that class and might be a question for @gavin-norman-sociomantic.

**Comment by mihails-strasuns** [comment]
AFAIU `opIn` is already present and works like `opApply` after this change. See the discussion linked from the issue.

**Comment by matthias-wende-sociomantic** [comment]
> AFAIU opIn is already present and works like opApply after this change.

Yes that's true. What I mean is that due to this patch it will change the semantics of the `opApply`. Instead it would also be possible to change how the `opIn` works by overriding the `opIn` from the super class.

**Comment by mihails-strasuns** [comment]
Right, but why would you want that? To me excluding unregistered elements makes more sense considering this is a derived class with sole purpose of limiting set of expected parameters.

**Comment by mihails-strasuns** [comment]
Replaced with https://github.com/sociomantic-tsunami/ocean/pull/696

**Pull request closed without merging**
