### PR TITLE
Fix closure for D2 builds

### PR DESCRIPTION
**Pull request by daniel-zullo**
Using closure causes GC allocation in D2 builds.
The problem was found setting the flag -vgc for DFLAGS.

### CODE REVIEW

**Comment by daniel-zullo** [comment]
There is another closure here:
https://github.com/sociomantic-tsunami/ocean/blob/v3.6.x/src/ocean/task/util/Timer.d#L105-L106

But I'm not entirely sure if it's right to make it `scope` in this special case.

**Comment by david-eckardt-sociomantic** [comment]
> But I'm not entirely sure if it's right to make it `scope` in this special case.

Make it `scope`, please: Later in the function the delegate is unregistered before the function returns, and this is documented with code comments.

**Comment by daniel-zullo** [comment]
Updated based on a suggestion from David. And rebased it against v3.7.x

**Review by david-eckardt-sociomantic — APPROVED** [review]

**Comment by daniel-zullo** [comment]
Thanks! :+1:

**Comment by david-eckardt-sociomantic** [comment]
Thank you!

**Pull request merged**
