### PR TITLE
Improve POSIX portability & work around #716

### PR DESCRIPTION
**Pull request by Geod24**
I needed `WallClock` and `Clock` to compile on OSX, hence switching to POSIX imports.
Also we're using `dub` to compile our code and a little `_` is all it takes to make it usable.

### CODE REVIEW

**Comment by Geod24** [comment]
The failing test is a network error, can someone restart it ?

**Comment by ben-palmer-sociomantic** [comment]
> The failing test is a network error, can someone restart it ?

Done

**Comment by ben-palmer-sociomantic** [comment]
And again.

**Comment by Geod24** [comment]
Rebased on v5.x.x

**Review by matthias-wende-sociomantic — APPROVED** [review]

**Pull request merged**
