### PR TITLE
Update Makd to v3.0.1

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Comment by joseph-wakeling-frequenz** [comment]
This is failing because the `Version.Id` template was not correctly modified when D2 support was dropped.  Fix for makd here:
https://github.com/sociomantic-tsunami/makd/pull/136

**Comment by joseph-wakeling-frequenz** [comment]
I've created the [makd v3.0.1 release](https://github.com/sociomantic-tsunami/makd/releases/tag/v3.0.1), so this can be updated now.

**Review by joseph-wakeling-frequenz — APPROVED** [review]
Commit LGTM, PR title needs an edit too :-)

**Comment by Geod24** [comment]
Done

**Comment by joseph-wakeling-frequenz** [comment]
All LGTM, thanks!

**Pull request merged**
