### PR TITLE
Deprecate functions using creal or ireal

### PR DESCRIPTION
**Pull request by Geod24**
At least I know who'll review this :)

### CODE REVIEW

**Review by alaksiej-stankievicx-dunnhumby — APPROVED** [review]
LGTM
Do you expect me to review it?

**Comment by alaksiej-stankievicx-dunnhumby** [comment]
Hmm, it seems these changes somewhat affect template instantiation somewhere else.

**Comment by ibuclaw** [comment]
Yeah, the testsuite results say that there's a little more that needs to be done in order to get it working.

**Comment by Geod24** [comment]
Yep, needs to deal with `isFloatingPoint`.

**Comment by Geod24** [comment]
Worked around by not deprecating the `isComplexType`. I don't think there's any users, and if there is, well the next major is going to break their code.

**Comment by alaksiej-stankievicx-dunnhumby** [comment]
> Worked around by not deprecating the `isComplexType`. I don't think there's any users, and if there is, well the next major is going to break their code.

Maybe add something via pragma(msg) to notify people to stop using this function but without actual depreciation?

**Comment by Geod24** [comment]
> Maybe add something via pragma(msg) to notify people to stop using this function but without actual depreciation?

Well it's used in `isFloatingPoint`, so it would trigger in unrelated code.

**Comment by Geod24** [comment]
Rebasing now, and will test in our application to see if other deprecations are being triggered.

**Comment by Geod24** [comment]
I can confirm, all gone :)

**Pull request merged**
