### PR TITLE
Deprecate ocean.transition : getMsg

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
```
As mentioned in the release notes, it always resolves to `Exception.message()` nowadays.
```

@mihails-strasuns-sociomantic mentioned that this is now possible.
However, I recommend not to merge before libraries are adapted, otherwise there will be a cascade of useless deprecation messages.

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
XREF https://github.com/dlang/druntime/commit/e7e49cd206dec5324f9f4baf56099e211d8f9c9e

**Comment by mihails-strasuns-sociomantic** [comment]
@mathias-lang-sociomantic can you split switching to `message` into a separate PR so that this one remains only a deprecation? We can merge the former right away.

**Comment by mathias-lang-sociomantic** [comment]
https://github.com/sociomantic-tsunami/ocean/pull/480

**Comment by mathias-lang-sociomantic** [comment]
Rebased

**Comment by mihails-strasuns-sociomantic** [comment]
@sociomantic-tsunami/core-team any objections against merging this in 3.9.0?

**Comment by nemanja-boric-sociomantic** [comment]
I think that should be fine, as long as we can use `.message` in downstream libraries that support ocean v3.x.x (to avoid needless deprecation spam). I'll check that.

**Comment by nemanja-boric-sociomantic** [comment]
I think this should be fine. There are few places in swarm/protos where we use `getMsg`, but that can be changed in the patch release, since the oldest compiler we support is dmd-transitional v2.070, which comes with `Throwable.message`.

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Pull request merged**
