### PR TITLE
Move ocean.util.log.model.ILogger outside model

### PR DESCRIPTION
**Pull request by Geod24**
A package with a single module is a red flag.
Also, see #573 for why this `model` thing is a bad idea.

### CODE REVIEW

**Review by ben-palmer-sociomantic — APPROVED** [review]
LGTM

**Comment by Geod24** [comment]
@shiv-tiwari-dunnhumby : Looks like this is missing form the release.

**Comment by Geod24** [comment]
Rebased on v5.x.x

**Review by daniel-zullo — APPROVED** [review]
LGTM

**Comment by daniel-zullo** [comment]
@Geod24 the branch v5.x.x is broken after merging this PR
```
./src/ocean/util/log/layout/LayoutSimple.d(26): Deprecation: module ocean.util.log.model.ILogger is deprecated - Import `ocean.util.log.ILogger` instead
Failed: ["dmd-transitional", "-g", "-O", "-inline", "-cov", "-I/home/travis/build/sociomantic-tsunami/ocean/build/production/include", "-I./src", submodules/makd/Makd.mak:595: recipe for target '/home/travis/build/sociomantic-tsunami/ocean/build/production/tmp/allunittests' failed
"-I./submodules/makd/src", "-I./submodules/beaver/src", "-w", "-version=GLIBC", "-de", "-L-lglib-2.0", "-L-lpcre", "-L-lxml2", "-L-lxslt", "-L-lebtree", "-L-lreadline", "-L-lhistory", "-L-llzo2", "-L-lbz2", "-L-lz", "-L-ldl", "-L-lgcrypt", "-L-lgpg-error", "-L-lrt", "-L-lssl", "-L-lcrypto", "-unittest", "-debug=UnitTest", "-version=UnitTest", "-v", "-o-", "/home/travis/build/sociomantic-tsunami/ocean/build/production/tmp/allunittests.d", "-I/home/travis/build/sociomantic-tsunami/ocean/build/production/tmp"]
make: *** [/home/travis/build/sociomantic-tsunami/ocean/build/production/tmp/allunittests] Error 1
```

It seems we will need to fix/update this line
https://github.com/sociomantic-tsunami/ocean/blob/v5.x.x/src/ocean/util/log/layout/LayoutSimple.d#L26

**Comment by Geod24** [comment]
Indeed, two of my PR conflicting. Will raise a new PR soon.

**Comment by daniel-zullo** [comment]
> @Geod24 the branch v5.x.x is broken after merging this PR
> 
> ```
> ./src/ocean/util/log/layout/LayoutSimple.d(26): Deprecation: module ocean.util.log.model.ILogger is deprecated - Import `ocean.util.log.ILogger` instead
> Failed: ["dmd-transitional", "-g", "-O", "-inline", "-cov", "-I/home/travis/build/sociomantic-tsunami/ocean/build/production/include", "-I./src", submodules/makd/Makd.mak:595: recipe for target '/home/travis/build/sociomantic-tsunami/ocean/build/production/tmp/allunittests' failed
> "-I./submodules/makd/src", "-I./submodules/beaver/src", "-w", "-version=GLIBC", "-de", "-L-lglib-2.0", "-L-lpcre", "-L-lxml2", "-L-lxslt", "-L-lebtree", "-L-lreadline", "-L-lhistory", "-L-llzo2", "-L-lbz2", "-L-lz", "-L-ldl", "-L-lgcrypt", "-L-lgpg-error", "-L-lrt", "-L-lssl", "-L-lcrypto", "-unittest", "-debug=UnitTest", "-version=UnitTest", "-v", "-o-", "/home/travis/build/sociomantic-tsunami/ocean/build/production/tmp/allunittests.d", "-I/home/travis/build/sociomantic-tsunami/ocean/build/production/tmp"]
> make: *** [/home/travis/build/sociomantic-tsunami/ocean/build/production/tmp/allunittests] Error 1
> ```
> 
> It seems we will need to fix/update this line
> https://github.com/sociomantic-tsunami/ocean/blob/v5.x.x/src/ocean/util/log/layout/LayoutSimple.d#L26

Fixed in #767

**Pull request merged**
