### PR TITLE
docker: Use sociomantictsunami/dlang base image

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
Also remove some boilerplate from Travis scripts.

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
Can you base it on v2.6.x please so that point releases also benefit from faster testing?

**Comment by leandro-lucarella-sociomantic** [comment]
Done, also fixed the docker image tag (missing `v1-`)

**Comment by mihails-strasuns-sociomantic** [comment]
Probably missing `apt-get update`?

**Comment by leandro-lucarella-sociomantic** [comment]
Yeah, it was relying on the previous scripts doing so I guess...

**Comment by leandro-lucarella-sociomantic** [comment]
Boom!

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Comment by mihails-strasuns-sociomantic** [comment]
So, let's re-iterate further plan of actions:

1) You will create cachalote repo which will host both scripts for generating images and scripts to be reused for travis CI integration
2) dlang image generation will be based on current content of internal sociomantic/dlang repo
3) once cachalote is ready, we enable matrix jobs in ocean by `sed`ing `Dockerfile` to change base image versions

Correct?

**Comment by leandro-lucarella-sociomantic** [comment]
> You will create cachalote repo which will host both scripts for generating images and scripts to be reused for travis CI integration

[Done](https://github.com/sociomantic-tsunami/cachalot)

> dlang image generation will be based on current content of internal sociomantic/dlang repo

This is undecided but let's talk about it internally...

> once cachalote is ready, we enable matrix jobs in ocean by seding Dockerfile to change base image versions

Yes, the idea is to add the support / boilerplate scripts to achieve this in cachalot.

**Comment by leandro-lucarella-sociomantic** [comment]
* https://github.com/sociomantic-tsunami/cachalot/issues/1
* https://github.com/sociomantic-tsunami/cachalot/issues/2

**Pull request merged**
