### PR TITLE
Fix code coverage report generation

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
Seems like https://github.com/sociomantic-tsunami/ocean/pull/123 was not sufficient despite being green and reporting no errors in log. Investigating.

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
@leandro-lucarella-sociomantic works again - sadly it seems necessary for docker container to be mounted in repo root as codecov bash script makes heavy use of `git` commands. Adding workarounds for that should be possible but I would prefer to simply get it working for now. Do we expose anything sensitive this way?

**Comment by leandro-lucarella-sociomantic** [comment]
I think we can leave it like this for now, nothing occurs to me that could leak, it's just general distrust given how bad the codecov script it and how badly maintained the repo for it is too.

**Comment by leandro-lucarella-sociomantic** [comment]
So it says we are at 60% line coverage, but the circle's graph doesn't look like it at all... is that correct?

https://codecov.io/gh/sociomantic-tsunami/ocean

**Comment by leandro-lucarella-sociomantic** [comment]
Ahhh, 90% is still barely green (which makes sense), that's why it's all red... :man_facepalming:

**Comment by mathias-lang-sociomantic** [comment]
I just looked at the report for the formatter and it looks like there are a couple of bugs on coverage as well :(

**Pull request merged**
