### PR TITLE
Correct HTTP status phrase for 200

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
As requested by @federico-cuello-sociomantic

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
Jokes aside I would be really curious to check it with some of our internal HTTP projects first to see if some weird legacy module no one has touched for years breaks.

**Review by leandro-lucarella-sociomantic — COMMENTED** [review]
Same as @mihails-strasuns-sociomantic, also, I would like to see some sort of reasoning behind this besides being recommended by Fede. Why did he recommended this? Was it violating a RFC? Etc.

**Comment by leandro-lucarella-sociomantic** [comment]
I'm tempted to mark this as a breaking change. Is one of those things that in theory is **should** be harmless but that then triggers all sorts of obscure bugs :)

Unless this is a bug fix, and even then if there is no urgency for this, I would put it in the next major, just for potential risk and being totally unexpected.

**Comment by federico-cuello-sociomantic** [comment]
:man_shrugging: ok, I saw it when checking a response from jet (it just looked "wrong") and the RFC is using all upper case but it's not *against* the RFC per se.

https://tools.ietf.org/html/rfc7231#section-6.3.1

**Comment by mihails-strasuns-sociomantic** [comment]
Yeah I agree with @leandro-lucarella-sociomantic , better move it to next major in that case

**Comment by mathias-lang-sociomantic** [comment]
Rebased on v4.x.x

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Review by mihails-strasuns-sociomantic — CHANGES_REQUESTED** [review]
Release notes :)

**Comment by mathias-lang-sociomantic** [comment]
Done. Note that some files in `relnotes` should probably be deleted for v4 :)

**Comment by mihails-strasuns-sociomantic** [comment]
What do you mean? AFAICS https://github.com/sociomantic-tsunami/ocean/tree/v4.x.x/relnotes has only one file and it is indeed for v4.x.x

**Comment by mathias-lang-sociomantic** [comment]
My bad, my v4.x.x was badly out of sync.

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Pull request merged**
