### PR TITLE
Override IConnectionHandler.unregisterSocket in TaskConnectionHandler

### LINKED ISSUE #325: Implement IConnectionHandler.unregisterSocket in TaskConnectionHandler

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
TaskConnectionHandler should override
IConnectionHandler.unregisterSocket to unregister the transiver's socket
from epoll prior to closing it, as closing socket doesn't guarantee that
the socket will be unregistered from the epoll.

Fixes #325

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
Not sure if this is a bugfix, or a feature or both.

**Comment by gavin-norman-sociomantic** [comment]
This PR gives me deja vu :thinking:

**Comment by gavin-norman-sociomantic** [comment]
Ah I see, this is a v3.x.x companion to https://github.com/sociomantic-tsunami/ocean/pull/377 :+1:

**Comment by gavin-norman-sociomantic** [comment]
This feels like a bug fix to me.

**Comment by nemanja-boric-sociomantic** [comment]
All right, will retarget. I got confused by the milestone.

**Comment by nemanja-boric-sociomantic** [comment]
Rebased to v3.4.x

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Pull request merged**
