### PR TITLE
Refactor serializer

### PR DESCRIPTION
**Pull request by david-eckardt-sociomantic**
Improve a few things I came across in #80.

Based on #80, to be rebased on v2.x.x when #80 and v2.6.x are merged. Blocked until then.

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
#80 is merged, and v2.6.x is merged into v2.x.x. I guess this needs rebase and change of the target branch (to target v2.x.x).

**Comment by mihails-strasuns-sociomantic** [comment]
@david-eckardt-sociomantic please rebase

**Comment by mihails-strasuns-sociomantic** [comment]
@david-eckardt-sociomantic please rebase

**Comment by david-eckardt-sociomantic** [comment]
What happened? I was just about to rebase it...

**Comment by mihails-strasuns-sociomantic** [comment]
v2.6.x branch got deleted post ocean release ;) please re-create against v2.x.x

**Comment by david-eckardt-sociomantic** [comment]
ok

**Pull request closed without merging**
