### PR TITLE
Remove bogus out contract from IncrementalValue dtor.

### PR DESCRIPTION
**Pull request by iain-buclaw-sociomantic**
There is a proposed patch in upstream DMD which now rejects modifying the 'this' parameter inside a contract, and this is one place that errors when the patch is applied.

Looking at the code, it indeed does look like a logic bug.

### CODE REVIEW

**Review by mathias-lang-sociomantic — APPROVED** [review]

**Review by mihails-strasuns-sociomantic — APPROVED** [review]
Complaints about DMD generating broken `-release` builds feel particularly good in this context :trollface:

**Comment by mihails-strasuns-sociomantic** [comment]
I will look into adding some simple tests to this module too, before merging.

**Comment by mihails-strasuns-sociomantic** [comment]
Added test, merging

**Comment by wilzbach** [comment]
Awesome guys!
Any chance we can get this into the `v4` branch too?
It's blocking https://github.com/dlang/dmd/pull/7553 from being merged.

See also: https://github.com/dlang/ci/blob/master/vars/runPipeline.groovy#L165

**Comment by mihails-strasuns-sociomantic** [comment]
Sure, I will submit pipeline PR after tagging new v4 RC.

**Comment by mihails-strasuns-sociomantic** [comment]
@wilzbach https://github.com/dlang/ci/pull/108

**Pull request merged**
