### PR TITLE
Switch back to manual codecov.sh call

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
Checking if it will fix double-comment and malformed report problem we have now.

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
> Checking if it will fix double-comment and malformed report problem we have now.

Malformed report? Maybe you can do a test here with the same arguments beaver uses to see if there is a problem with the script version or to identify if it's some argument that breaks it?

**Review by leandro-lucarella-sociomantic — COMMENTED** [review]
Just a comment to "ACK" the review request :D

**Comment by mihails-strasuns-sociomantic** [comment]
> Maybe you can do a test here with the same arguments beaver uses to see if there is a problem with the script version or to identify if it's some argument that breaks it?

Yep, now that we see that reverting to old command fixes the issue I will try adding tweaks from beaver one by one.

**Comment by mihails-strasuns-sociomantic** [comment]
Closing as problem was confirmed to be on codecov side

**Pull request closed without merging**
