### PR TITLE
Trivial: Fix some style issues in ConfigParser

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
I had this bitrotting in one of my branch, might as well submit it...

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
And of course there's coverage decrease those documented unittests aren't run (since they do I/O).

**Comment by mihails-strasuns-sociomantic** [comment]
That is fine, importance of coverage check is mostly for new big additions. I wish I could configure it to never result in CI status failure but that doesn't seem possible :(

**Review by mihails-strasuns-sociomantic — APPROVED** [review]
LGTM but would be nice for someone more familiar with config parser to have a look

**Comment by mathias-lang-sociomantic** [comment]
Maybe @nemanja-boric-sociomantic ?

**Comment by nemanja-boric-sociomantic** [comment]
ACK

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Pull request merged**
