### PR TITLE
Properly escape OCEAN_D2_USER OCEAN_D2_PASS

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
Noticed in and based on #223

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
It doesn't really need to be based on the other one ;)

**Comment by nemanja-boric-sociomantic** [comment]
I'm curious why it fails: https://travis-ci.org/sociomantic-tsunami/ocean/jobs/267559688#L1409

Should it be maybe:

```
BEAVER_DOCKER_VARS=... test "$AFTER_SCRIPT" = "1" && beaver run ci/d2tags.sh
```

?

**Comment by mihails-strasuns-sociomantic** [comment]
Yeah could be the case. I thought one can define env var at start of any expression but it doesn't seem to be the case!

**Comment by nemanja-boric-sociomantic** [comment]
OK, I got it. Turns out there's no need for any escaping in travis.yml.

**Review by mihails-strasuns-sociomantic — APPROVED** [review]
Even better!

**Pull request merged**
