### PR TITLE
Add support for Ubuntu bionic

### PR DESCRIPTION
**Pull request by daniel-zullo**
- Remove D1 flags which are no longer needed as the code base is only D2.
- Set libssl and libcrypto to version 1.0.0 supported in Ubuntu xenial and bionic.
- The dmd-transitional compiler is available for Ubuntu bionic only in vesion 2.078.3.s*.
- Update beaver build image to support Ubuntu xenial and bionic distributions.
- Remove package d1to2fix that is no longer required as the code base is only D2.
- Add -fPIC to dmd-transitional as Ubuntu bionic requires builds to use position independent code and dmd-compiler does not set the flag -fPIC by default

### CODE REVIEW

**Comment by daniel-zullo** [comment]
Blocked on `libssl-dev` as the version provided in bionic (`1.1.1-1ubuntu2.1~18.04`) by default does not provides these symbols:

```
/home/travis/build/sociomantic-tsunami/ocean/./src/ocean/net/ssl/SslClientConnection.d:479: undefined reference to `SSL_library_init'
/home/travis/build/sociomantic-tsunami/ocean/./src/ocean/net/ssl/SslClientConnection.d:483: undefined reference to `SSL_load_error_strings'
/home/travis/build/sociomantic-tsunami/ocean/./src/ocean/net/ssl/SslClientConnection.d:488: undefined reference to `SSLv23_method'
```

**Comment by daniel-zullo** [comment]
> Blocked on `libssl-dev` as the version provided in bionic (`1.1.1-1ubuntu2.1~18.04`) by default does not provides these symbols:
> 
> ```
> /home/travis/build/sociomantic-tsunami/ocean/./src/ocean/net/ssl/SslClientConnection.d:479: undefined reference to `SSL_library_init'
> /home/travis/build/sociomantic-tsunami/ocean/./src/ocean/net/ssl/SslClientConnection.d:483: undefined reference to `SSL_load_error_strings'
> /home/travis/build/sociomantic-tsunami/ocean/./src/ocean/net/ssl/SslClientConnection.d:488: undefined reference to `SSLv23_method'
> ```

~Pushed symlinks to the current supported version, this temporal hack is the simplest solution I've found so far~

**Comment by daniel-zullo** [comment]
Setting the specific version of libssl in Build.mak might be a better solution. I'll try it out

**Comment by daniel-zullo** [comment]
Set version of libssl in Build.mak instead

**Review by ben-palmer-sociomantic — APPROVED** [review]
LGTM

**Comment by daniel-zullo** [comment]
Set libcrypto to the same version than libssl.

**Comment by ben-palmer-sociomantic** [comment]
LGTM but maybe someone else could take a quick look.

**Comment by daniel-zullo** [comment]
Block on dmd-transitional

**Comment by daniel-zullo** [comment]
Removed 620cd5dd and it is no longer blocked on dmd-transitional. I'll push a new PR as I cannot reopen it

**Comment by daniel-zullo** [comment]
Done in #789

**Pull request closed without merging**
