### PR TITLE
README: Update build badge for v2.6.x

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
This might be annoying to remember, I don't really know what to do about
it. We can try to keep it up to date for now.

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
Could we just use the default branch ? It doesn't bring too much to do it every time, does it ?

**Comment by mihails-strasuns-sociomantic** [comment]
Yeah I agree with @mathias-lang-sociomantic , the main purpose of the badge is to show current build status in the rendered readme - keeping it tied to current branch is just an extra maintenance effort.

**Comment by mihails-strasuns-sociomantic** [comment]
Updated to use default branch instead

**Comment by leandro-lucarella-sociomantic** [comment]
> Could we just use the default branch ? It doesn't bring too much to do it every time, does it ?

That's misleading, what sense does it make to see that some other branch is green when I'm looking at another particular branch. I would rather completely remove the badge instead if we don't care to keep it up to date.

I don't think is that much of a trouble to update the badge (it will just be easy to forget). We already have a lot of bookeeping to do when we make a release, updating the badge should be a non-brainer when we have scripts for this.

**Comment by leandro-lucarella-sociomantic** [comment]
Sorry, force pushed again with my original commit, I prefer to leave the changes in this PR consistent with what the PR was created for, if you want another solution just create another PR.

**Comment by mihails-strasuns-sociomantic** [comment]
I'd like to close this PR as wontfix in that case, as I strongly object the practice you are trying to introduce here.

**Comment by mathias-lang-sociomantic** [comment]
> That's misleading, what sense does it make to see that some other branch is green when I'm looking at another particular branch.

The root issue here is that there is no way to use the current branch as a parameter to anything in markdown. It's a well-known Github limitation, and I don't find it particularly misleading (but would really like for it to be solved as well).

**Comment by mihails-strasuns-sociomantic** [comment]
Competing PR to remove the badge: https://github.com/sociomantic-tsunami/ocean/pull/29

**Comment by leandro-lucarella-sociomantic** [comment]
Again I don't think is a huge burden to keep it updated and it can be automatized, but I'm also fine with removing the badge completely. When I see an alternative PR to solve this in another consistent way, I'll happily close as won't fix.

**Pull request closed without merging**
