### PR TITLE
Use Makd COV option to get coverage

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
With this, even integration tests should get coverage reports.

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
For dmd 2.070.2.s* and 2.071.2.s* no coverage reports are produced. Do we have a dmd-transitional actually released with the cov merging? For 2.078.* now nothing is produced either but I think it worked before I changed to use the `COVDIR`, so I will investigate that.

**Comment by leandro-lucarella-sociomantic** [comment]
Damn, in upstream DMD using env vars to configure the runtime is disabled by default. Each program needs to enable it, so I guess MakD needs to switch to use command-line arguments for D2

**Comment by leandro-lucarella-sociomantic** [comment]
New dmd-transitional releases with support to customize coverage were released, so re-triggering the tests! 🤞

**Comment by leandro-lucarella-sociomantic** [comment]
OK, all seems to work now judging from the Travis logs, but I wanted to see the differences in coverage and codecov can't show the page 😒

**Comment by mihails-strasuns-sociomantic** [comment]
`will increase coverage by 6.18%` :notbad:

**Comment by mihails-strasuns-sociomantic** [comment]
@leandro-lucarella-sociomantic I was able to see it after visiting codecov main page first, authorizing and then manually navigating through project/PR list.

**Comment by mihails-strasuns-sociomantic** [comment]
.. not anymore :grumpy:

**Comment by leandro-lucarella-sociomantic** [comment]
And the status page says everything is OK ✨

**Comment by nemanja-boric-sociomantic** [comment]
I've seen this before, I don't think this is related to this. I had PRs for which it simply didn't work. I would recommend re-pushing and see what will happen.

**Comment by leandro-lucarella-sociomantic** [comment]
OK, I will use makd v2.2.0-rc.1 and see

**Comment by nemanja-boric-sociomantic** [comment]
```
Submodule 'beaver' (https://github.com/leandro-lucarella-sociomantic/beaver.git) registered for path 'submodules/beaver'
Submodule 'makd' (https://github.com/sociomantic-tsunami/makd.git) registered for path 'submodules/makd'
Cloning into '/home/travis/build/sociomantic-tsunami/ocean/submodules/beaver'...
Cloning into '/home/travis/build/sociomantic-tsunami/ocean/submodules/makd'...
error: Server does not allow request for unadvertised object c50508d76fa97557c68ea4e7f914ff080a187ea7
Fetched in submodule path 'submodules/beaver', but it did not contain c50508d76fa97557c68ea4e7f914ff080a187ea7. Direct fetching of that commit failed.```

**Comment by nemanja-boric-sociomantic** [comment]
Looking at https://codecov.io/gh/sociomantic-tsunami/ocean/pulls all links to diff coverage result in Application error.

**Comment by leandro-lucarella-sociomantic** [comment]
> Looking at https://codecov.io/gh/sociomantic-tsunami/ocean/pulls all links to diff coverage result in Application error.

For me is "Sorry...unable to process your request. Visit http://status.codecov.io for more information." And no reply from codecov. Does anyone have a twitter account to rant? These days it seems the only way to get some attention 🤣

**Comment by leandro-lucarella-sociomantic** [comment]
Updated with new beaver v0.4.0-rc.1 release (removed WIP and blocked).

**Comment by leandro-lucarella-sociomantic** [comment]
OK, beaver release is not tagged as final. I would merge this and see if it fixes codecov display issues.

**Comment by nemanja-boric-sociomantic** [comment]
ok.

**Pull request merged**
