### PR TITLE
Zero pad milliseconds to 3 places

### PR DESCRIPTION
**Pull request by andrew-stevenson-sociomantic**
Reverts behavioural change from dcf428aa

### CODE REVIEW

**Comment by andrew-stevenson-sociomantic** [comment]
@Geod24 FYI

**Review by alaksiej-stankievicx-dunnhumby — APPROVED** [review]
LGTM

You probably may comment in commit message more on the reason why this reverting is important.
And also if this behaviour is required it is good to add unittest on it to prevent problems in the future.

**Comment by andrew-stevenson-sociomantic** [comment]
Well its not really that important apart from stopping it looking odd. If other things happen to have depended on the format always using 0 padding then that is really more a bug with them.

The real problem was the un-noticed behavioural change - but that was presumably accidental. A unittest might have caught that but given this method now largely just calls sformat (presumably already tested) we are really only testing no one changes the format string - and that seems unlikely for anyone to do without due consideration. If someone does decide to re-write it again then comparing old a new behaviour can be a task for them.

**Review by christoph-wasicki-sociomantic — APPROVED** [review]

**Comment by Geod24** [comment]
Oops, good catch!

> A unittest might have caught that

There was no unittest in place for those classes at the time. So the first thing I did was to introduce an unittest, but the value I used did not exhibit the issue.

**Review by Geod24 — APPROVED** [review]

**Review by ben-palmer-sociomantic — APPROVED** [review]
LGTM

**Pull request merged**
