### PR TITLE
Remove all "imports" comment blocks

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
Maybe we should wait with other large chunks of code changes (asserts -> verify) being merged first, to avoid conflicts?

**Comment by mihails-strasuns-sociomantic** [comment]
I did it exactly so that I don't need to split it into separate commits in my verify PRs :P

**Review by gavin-norman-sociomantic — APPROVED** [review]
Yeah why not. The time has probably come.

**Comment by gavin-norman-sociomantic** [comment]
Er... red...?

**Comment by mihails-strasuns-sociomantic** [comment]
Overly eager pattern matching :) Fixed

**Pull request merged**
