### PR TITLE
[WIP] (Re)Configurable loggers

### LINKED ISSUE #37: Allow to reconfigure loggers live from UnixSocket
Now that we have UnixSocket support in DaemonApp, it would be nice to get a set of basic commands in (which can be overriden / skipped if the dev wants to).

One of those would be the ability to change logger configurations live, so one can temporarily enable / disable some loggers for debugging purpose.

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
```
This commit add a default handler for the UnixSocket extension,
which allow one to reconfigure the loggers without restarting the app.
Connecting to the unix socket (through e.g. `nc`), one can send
commands such as `SetLogger set fully.qualified.name level=[Info,Fatal,...]`.

Potential enhancements being considered:
- Currently we only support 'propagate' and 'level'.
  What other properties would be interesting ? 'file' / 'layout' ?
- Currently we only support the 'set' command.
  One of the original idea is to also support 'reset'.
  But this would require to store the original config within the logger (arguably doesn't scale).
  Another option would be to add the ability to re-parse the config file(s).

Fixes #37
```

Just here so we don't loose track of it. The integration test passes (also tested with ocean v3, found a bug that I'll file separately). Will test with a real app soon :tm:

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
@mihails-strasuns-sociomantic : I assume coverage report doesn't include result of integration tests, only unittests ?

**Comment by mihails-strasuns-sociomantic** [comment]
@mathias-lang-sociomantic correct. I don't know if there is any way/tool to merge coverage reports from multiple runs so if we allowed `-cov` in integration tests, those would overwrite previous ones.

**Comment by mihails-strasuns-sociomantic** [comment]
Release notes, just in case ;)

**Comment by mathias-lang-sociomantic** [comment]
I still need to test this in an application, and see what other people's needs are.
Also I'm starting to consider making it a new logger only feature, which will simplify merging for you. But first we need to deprecate the old loggers.

**Comment by mathias-lang-sociomantic** [comment]
I removed the ability to configure old loggers, since there is now a P.R. to deprecate them, and made this target v3.x.x
This is now based / blocked on https://github.com/sociomantic-tsunami/ocean/pull/173

**Comment by mathias-lang-sociomantic** [comment]
Rebased on v3.x.x

Does someone have an interest in this feature and would like to give me pointer to the needed features ?
CC @daniel-zullo-sociomantic  @joseph-wakeling-sociomantic @andrew-stevenson-sociomantic

**Comment by andrew-stevenson-sociomantic** [comment]
We are a way off being able to make use of it but I can see that being able to set file would be useful if not too difficult. Before upping the level of a particular logger its likely we would want to go to it's own file

**Comment by mihails-strasuns-sociomantic** [comment]
@mathias-lang-sociomantic what is the current state of this? I am for last v2 (v2.10.0) release in about two weeks, wonder if this PR can be ready by that time.

**Comment by mathias-lang-sociomantic** [comment]
>  I am for last v2 (v2.10.0) release in about two weeks, wonder if this PR can be ready by that time.

I don't know if it'll be ready, but this is targetting v3.x.x nowadays (the milestone wasn't changed)

**Comment by mihails-strasuns-sociomantic** [comment]
Oops! Thanks :)

**Comment by gavin-norman-sociomantic** [comment]
Not ready for v3.5.0. Moved to future. Can be moved into a release milestone again when ready.

**Comment by daniel-zullo** [comment]
I think we should support enabling/disabling `console`

> Another option would be to add the ability to re-parse the config file(s).

IMO this is a useful feature to have.

**Comment by mathias-lang-sociomantic** [comment]
I think this will need a bit of love from someone else.

**Pull request closed without merging**
