### PR TITLE
Remove meaningless destructor

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
No point in setting length of internal field to 0 upon destruction of
host object

### CODE REVIEW

**Review by gavin-norman-sociomantic — APPROVED** [review]
Indeed, seems pointless.

**Comment by gavin-norman-sociomantic** [comment]
Oh I just noticed this is done as part of a patch release. How come?

**Comment by mihails-strasuns-sociomantic** [comment]
Well, it isn't a feature and it causes invalid memory operation error in nautica when compiled with `-profile=gc` :)

**Comment by gavin-norman-sociomantic** [comment]
I see. (Normally it'd count as a refactoring.)

**Pull request merged**
