### PR TITLE
Support copying empty Contiguous instances

### PR DESCRIPTION
**Pull request by joseph-wakeling-sociomantic**
The original implementation of `ocean.serialize.contiguous.Util.copy` will throw a `SanityException` if `src` contains no data, because the `Deserializer.deserialize` method requires that underlying struct data is present.

This patch fixes the issue by ensuring `copy` checks `src.ptr` and then if it is `null` resets `dst` instead of deep-copying to it.

Note that we need to temporarily cast away `const`-ness of `src` to work around the fact that the `ptr` method does not currently support it.  We do not modify any underlying data, so this should not break the promise of the `copy` function signature.

Fixes https://github.com/sociomantic-tsunami/ocean/issues/652.

### CODE REVIEW

**Comment by joseph-wakeling-sociomantic** [comment]
Whoops, I forgot to target v4.2.x first time round.  Fixed for merge purposes, but CI seems to be embuggerated.  Can we get Travis to deal with this?  (Should be no big deal in any case since the patch is trivial and tests based on v4.x.x should be as valid as with v4.2.x.)

**Comment by nemanja-boric-sociomantic** [comment]
> Whoops, I forgot to target v4.2.x first time round. Fixed for merge purposes, but CI seems to be embuggerated. Can we get Travis to deal with this? (Should be no big deal in any case since the patch is trivial and tests based on v4.x.x should be as valid as with v4.2.x.)

Amend and force push should make Travis happy again.

**Comment by joseph-wakeling-sociomantic** [comment]
Done.  I've taken the opportunity to tweak the commit message slightly.

**Review by matthias-wende-sociomantic — APPROVED** [review]
Sounds totally reasonable and lgtm. Still I'll keep merging the PR to someone with deeper ocean experience.

**Comment by joseph-wakeling-sociomantic** [comment]
@mihails-strasuns is probably the one who should give final OK.

**Review by mihails-strasuns — APPROVED** [review]

**Pull request merged**
