### PR TITLE
Add ocean.io.Path.isReadable

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
Complementary to Path.isWritable, Path.isReadable is now added.

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
Blocked on v3.4.9 (which adds integration test for `isWritable`)

**Comment by nemanja-boric-sociomantic** [comment]
Moved to v3.7.0 milestone.

**Comment by mihails-strasuns-sociomantic** [comment]
Unblocked, please rebase

**Comment by nemanja-boric-sociomantic** [comment]
Rebased.

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Pull request merged**
