### PR TITLE
HttpException: Use catch (Exception) instead of pokemon catch

### PR DESCRIPTION
**Pull request by Geod24**
Pokemon catch is deprecated.

### CODE REVIEW

**Review by gavin-norman-sociomantic — APPROVED** [review]
This is on a minor release branch as it doesn't affect currently supported compiler versions, right?

**Comment by mihails-strasuns-sociomantic** [comment]
It affects any D2 compiler by not trying to catch `Error` anymore. I still think it is acceptable.

**Comment by mathias-lang-sociomantic** [comment]
We don't intend (and and couldn't without some effort) support upstream compiler in v3.x.x. I think that should be a reasonable goal for v4.x.x though.

**Comment by mihails-strasuns-sociomantic** [comment]
It is actually inside unittest, so doesn't matter at all :)

**Comment by mathias-lang-sociomantic** [comment]
Oh I think this part was obvious :P

**Comment by mihails-strasuns-sociomantic** [comment]
You have overestimated me :)

**Pull request merged**
