### PR TITLE
[docker/ci] Use tagged makd release for packaging dmds

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
tags are for forever

### CODE REVIEW

**Review by leandro-lucarella-sociomantic — APPROVED** [review]
Yeah, that was a silly thing to do.

**Comment by leandro-lucarella-sociomantic** [comment]
So this should be promptly merged to the other branches, right?

**Comment by nemanja-boric-sociomantic** [comment]
Correct. But as a bonus point, I think we're at stage where we can release v2.5.6.

**Comment by leandro-lucarella-sociomantic** [comment]
> Correct. But as a bonus point, I think we're at stage where we can release v2.5.6.

we don't really need to release to do a merge anyway. :)

**Pull request merged**
