### PR TITLE
Replace usage of ocean's socket module with druntime's

### PR DESCRIPTION
**Pull request by Geod24**
Let's see if it breaks 🤷‍♂

### CODE REVIEW

**Comment by Geod24** [comment]
Great, this works. After this, there's only two (legit) references to `socket` and references to `un` left:
```console
% grep -nR "ocean.stdc.posix.sys" src
src/ocean/net/server/SelectListener_slowtest.d:31:import ocean.stdc.posix.sys.un;
src/ocean/net/server/unix/UnixListener.d:111:    import ocean.stdc.posix.sys.un: sockaddr_un;
src/ocean/net/collectd/Collectd.d:95:import ocean.stdc.posix.sys.un;
src/ocean/stdc/posix/sys/utsname.d:15:module ocean.stdc.posix.sys.utsname;
src/ocean/stdc/posix/sys/shm.d:15:module ocean.stdc.posix.sys.shm;
src/ocean/stdc/posix/sys/select.d:15:module ocean.stdc.posix.sys.select;
src/ocean/stdc/posix/sys/socket.d:15:module ocean.stdc.posix.sys.socket;
src/ocean/stdc/posix/sys/statvfs.d:15:module ocean.stdc.posix.sys.statvfs;
src/ocean/stdc/posix/sys/uio.d:15:module ocean.stdc.posix.sys.uio;
src/ocean/stdc/posix/sys/types.d:15:module ocean.stdc.posix.sys.types;
src/ocean/stdc/posix/sys/stat.d:15:module ocean.stdc.posix.sys.stat;
src/ocean/stdc/posix/sys/wait.d:15:module ocean.stdc.posix.sys.wait;
src/ocean/stdc/posix/sys/ipc.d:15:module ocean.stdc.posix.sys.ipc;
src/ocean/stdc/posix/sys/un.d:15:module ocean.stdc.posix.sys.un;
src/ocean/stdc/posix/sys/mman.d:15:module ocean.stdc.posix.sys.mman;
src/ocean/sys/socket/UnixSocket.d:20:import ocean.stdc.posix.sys.socket;
src/ocean/sys/socket/UnixSocket.d:21:import ocean.stdc.posix.sys.un;
src/ocean/sys/socket/model/ISocket.d:19:import ocean.stdc.posix.sys.socket;
src/ocean/sys/socket/model/ISocket.d:1279:// TODO: Replace with import ocean.stdc.posix.sys.socket: accept4
% grep -nR "ocean.stdc.posix.sys" integrationtest
integrationtest/unixsocket/main.d:28:import ocean.stdc.posix.sys.un;
integrationtest/unixlistener/main.d:33:import ocean.stdc.posix.sys.un;
integrationtest/selectlistener/main.d:30:import ocean.stdc.posix.sys.un;
integrationtest/reopenfiles/main.d:25:import ocean.stdc.posix.sys.un;
```

I'll deal with them separately since the `socket` one needs to have constants moved into druntime, and the `un` one has a definition of `sockaddr` and a `create` method that needs deprecation.

CC @don-clugston-sociomantic

**Comment by Geod24** [comment]
Travis seem to have lost the notification, so force pushing for nothing.

**Comment by don-clugston-sociomantic** [comment]
Looks like Travis is asleep

**Comment by Geod24** [comment]
It's processing but somehow not reporting: https://travis-ci.org/github/sociomantic-tsunami/ocean/pull_requests

**Comment by don-clugston-sociomantic** [comment]
Finally it has completed, and passed.  LGTM

**Pull request merged**
