### PR TITLE
Remove mention of deleted v4.x.x in README

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Comment by ben-palmer-sociomantic** [comment]
Do we need to remove this? Its historical information that might be useful to someone and the tag is still present.

**Comment by Geod24** [comment]
The section name is "Maintained Major Branches"

**Comment by ben-palmer-sociomantic** [comment]
> The section name is "Maintained Major Branches"

Haha I should probably read before commenting I guess :)

**Comment by ben-palmer-sociomantic** [comment]
LGTM

**Pull request merged**
