### PR TITLE
[Trivial] Fix a bunch of typos

### PR DESCRIPTION
**Pull request by gkotian**

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
Can you rebase on top of v2.5.x? :)

**Comment by gkotian** [comment]
Done.

**Review by Burgos — APPROVED** [review]

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Comment by mathias-lang-sociomantic** [comment]
I see what you did here

**Comment by gkotian** [comment]
test this please travis

**Comment by gkotian** [comment]
>test this please travis

It was worth trying ¯\\\_(ツ)_/¯

**Comment by nemanja-boric-sociomantic** [comment]
Needs rebase :-)

**Comment by gkotian** [comment]
Rebased over latest `v2.5.x`.

**Pull request merged**
