### PR TITLE
Clear up some more extern(C) declarations

### PR DESCRIPTION
**Pull request by Geod24**
Better reviewed commit-by-commit.

### CODE REVIEW

**Comment by Geod24** [comment]
Travis, why are you like this ? Can someone retrigger the CI ? It's a network error...
CC @ben-palmer-sociomantic @don-clugston-sociomantic

**Comment by don-clugston-sociomantic** [comment]
This basically looks good, but could you please move the deprecation commits (timerfd, pthread) into a PR which is different from the cleanup stuff.  I notice that ThreadWorker is modified in both, so the cleanup one would have to be merged first,
If you split it off into a separate PR I will just merge them, we don't need to wait for Travis since we know it passes.

**Comment by Geod24** [comment]
Removed the two deprecation commits, will submit a new PR once this is merged.

**Comment by don-clugston-sociomantic** [comment]
LGTM

**Pull request merged**
