### PR TITLE
Compile ocean with -debug=ISelectClient in CI

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
Approximately every time someone needs to use debug=ISelectClient to
debug their application, they find it broken. This patch compiles Ocean
in Travis with this debug flag set.

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
I was a bit suspicious of this approach (used for the `-release` flag here: https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/.travis.yml#L25) so I've tested it with a broken commit and it doesn't work. (Meaning that our test for `-release` doesn't work as well, I guess).

cc @mihails-strasuns-sociomantic @leandro-lucarella-sociomantic

**Comment by nemanja-boric-sociomantic** [comment]
OK, last commit works, beaver PR incoming.

**Comment by nemanja-boric-sociomantic** [comment]
https://github.com/sociomantic-tsunami/beaver/pull/51

**Comment by mihails-strasuns-sociomantic** [comment]
Why just `ISelectClient`? If we go that way, more efficient to have one matrix element that enables all common debug flags at once.

**Comment by nemanja-boric-sociomantic** [comment]
> Why just ISelectClient? If we go that way, more efficient to have one matrix element that enables all common debug flags at once.

Yes, we can enable all debug flags at once, that's a good idea.

Updated beaver to v0.5.0.

**Comment by leandro-lucarella-sociomantic** [comment]
Travis says NO.

**Comment by nemanja-boric-sociomantic** [comment]
That is good, because I've added a commit that breaks `ISelectClient` so I know it actually doesn't compile. I'll rebase it now.

**Comment by nemanja-boric-sociomantic** [comment]
Updated.

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Pull request merged**
