### PR TITLE
Allow usage of Buffer!(char) and Buffer!(Wchar) with StringC.toStringC

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
`StringC`'s `toCString` overloads now support `Buffer!(char)` and
`Buffer!(Wchar)` as well as the arrays.

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
Is the `wchar` overload really necessary? I thought concensus was that we never use those and should slowly strip ocean code base from such overloads.

**Comment by nemanja-boric-sociomantic** [comment]
I'm not sure, but it's certainly a pain to maintain it and it makes the entire thing less readable. I would then go and remove that overload and create an issue to deprecate it in v4.x.x?

**Comment by mihails-strasuns-sociomantic** [comment]
Yeah I'd suggest to only support `Buffer!char` and deprecate `Wchar[]`.

**Comment by nemanja-boric-sociomantic** [comment]
Updated with `Buffer!char`. What do you feel - should we deprecate `Wchar[]` in v2.x.x, v3.x.x or v4.x.x. I feel deprecating in v2.x.x at the end of its lifetime could be a little bit too early?

**Comment by mihails-strasuns-sociomantic** [comment]
As far as I know we don't use any of those overloads anyway (which is why they are being deprecated in the first place) so v2.x.x is fine.

**Comment by nemanja-boric-sociomantic** [comment]
Deprecated.

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Pull request merged**
