### PR TITLE
Improve and fix ISuspendableThrottler style

### PR DESCRIPTION
**Pull request by matthias-wende-sociomantic**
See https://github.com/sociomantic-tsunami/ocean/pull/640#discussion_r223705069

### CODE REVIEW

**Comment by daniel-zullo** [comment]
There was also a comment about a missing `this.` that you might want to address in this patch

**Comment by mihails-strasuns** [comment]
Please rebase againt v4.x.x - refactoring and style fixes go to minor versions

**Comment by matthias-wende-sociomantic** [comment]
These just a style fixups for recent changes that were merged into v4.2.x a bit to early. Therefore I suggest to merge them to v4.2.x. I'll change the base branch back. If you still think they belong to to v4.x.x I have no problem with rebasing :).

**Comment by mihails-strasuns** [comment]
Ah, okay in that case.

**Pull request merged**
