### PR TITLE
Add LibFeatures entry for future 3.6.0

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
Need a new DMD ?

**Comment by mihails-strasuns-sociomantic** [comment]
I think only needed rebase, checking.

**Comment by mihails-strasuns-sociomantic** [comment]
Green

**Review by gavin-norman-sociomantic — APPROVED** [review]
Good to remember in advance :+1:

**Pull request merged**
