### PR TITLE
Refactor serializer (2)

### PR DESCRIPTION
**Pull request by david-eckardt-sociomantic**
Remake of #82

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
Looks good but I am really scared about merging it into v2.x.x because half of module will conflict.

Considering ocean v2.x.x has only 3 months of lifetime before end of support, maybe it makes sense to rebase this PR straight to v3.x.x ?

**Comment by mihails-strasuns-sociomantic** [comment]
Ping @david-eckardt-sociomantic

**Comment by mihails-strasuns-sociomantic** [comment]
Ping @david-eckardt-sociomantic

**Comment by david-eckardt-sociomantic** [comment]
test this please jenkins

**Comment by david-eckardt-sociomantic** [comment]
Rebased on v3.x.x.
Jenkins doesn't seem to test this, do I need to do something?

**Comment by nemanja-boric-sociomantic** [comment]
No Jenkins here :-)

**Comment by mihails-strasuns-sociomantic** [comment]
Maybe Travis is just slow, let's wait a bit

**Comment by david-eckardt-sociomantic** [comment]
Ah, Jenkins has been retired.

**Comment by mihails-strasuns-sociomantic** [comment]
@llucax @leandro-lucarella-sociomantic  any ideas why Travis ignores this?

**Comment by nemanja-boric-sociomantic** [comment]
This somehow magically got tested now.

**Comment by mihails-strasuns-sociomantic** [comment]
I amended last commit and pushed to @david-eckardt-sociomantic branch ;)

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Pull request merged**
